version: '2.4'

#x-typeorm: &typeorm-env
#  NODE_ENV: ${NODE_ENV}
#  EXPO_DEVTOOLS_LISTEN_ADDRESS: ${EXPO_DEVTOOLS_LISTEN_ADDRESS}
#  REACT_NATIVE_PACKAGER_HOSTNAME: ${REACT_NATIVE_PACKAGER_HOSTNAME}

services:
  area-mobile-app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
#      <<: *typeorm-env
#      - NODE_ENV=development
#      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
#      - REACT_NATIVE_PACKAGER_HOSTNAME=10.68.248.127
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    volumes:
      - ./area-mobile-app:/opt/area-mobile-app/app:delegated
      - ./area-mobile-app/package.json:/opt/area-mobile-app/package.json
      - ./area-mobile-app/package-lock.json:/opt/area-mobile-app/package-lock.json
      - notused:/opt/area-mobile-app/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: