blank_issues_enabled: false
contact_links:
  - name: Raccoon Support
    url: https://github.com/EpitechPromo2025/B-DEV-500-PAR-5-2-area-clement.fernandes/issues
    about: Please ask and answer questions here.