version: '3.9'

x-typeorm: &typeorm-env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  JWT_SECRET: ${JWT_SECRET}

volumes:
  postgres_data: {}

networks:
  authenticathor-network:
    external: false

services:

  postgres-db:
    image: postgres:14
    container_name: ${POSTGRES_HOST}
    environment:
      <<: *typeorm-env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - authenticathor-network
    volumes:
      - postgres_data:/var/lib/postgresql@14/data

  app:
    profiles:
      - app
      - all
    container_name: app
    build:
      dockerfile: development/Dockerfile
      context: ../
    networks:
      - authenticathor-network
    volumes:
      - ../src:/home/node/app/src
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      <<: *typeorm-env
    entrypoint: [ "npm", "run", "start:dev", "--tsc" ]