name: Markdown Links Checker

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
      branches: [main]
  push:
      branches: [main]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension: .md
        max-depth: 1
        base-branch: main
        file-path: ./README.md